version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Test API Server
  api:
    build:
      context: ./testServer
      dockerfile: Dockerfile
    ports:
      - "5009:5009"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5009/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Development services
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3102:3102"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    depends_on:
      - api-dev
    profiles:
      - dev

  api-dev:
    build:
      context: ./testServer
      dockerfile: Dockerfile
    ports:
      - "5009:5009"
    volumes:
      - ./testServer:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles:
      - dev